spring:
  application:
    name: homeowner
  cloud:
    services:
      registrationMethod: direct

---

spring:
  profiles: dev

security:
  basic:
    enabled: false

management:
  security:
    enabled: false
